### ISSUE TITLE
Get-TierZeroServicePrincipals -Token $MSGraphToken - Invalid arguments error

### ISSUE THREAD

**Issue by mpras01** [BloodHoundAD/BARK#8]
Hi,
I am running into the following error every time i try to fetch Get-TierZeroServicePrincipals

Get-TierZeroServicePrincipals -Token $MSGraphToken
select : Property "principal" cannot be found.
At C:\Users\Downloads\BARK.ps1:8276 char:28
+     $PartnerTier2Support | select -expand principal | ?{$_.'@odata.ty ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{@odata.contex...ystem.Object[]}:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand

**Comment by doubley612** [comment]
Just add "-ErrorAction Ignore" after "select -expand principal"

**Comment by superpb9** [comment]
Thanks. Got similar issues here after executing Get-EntraTierZeroServicePrincipals -Token XYZ ... I guess, it is because variable values of '$PrivAuthAdmins', '$PartnerTier2Support' are empty {} in the response ... Adding "-ErrorAction Ignore" does solve the issue for now but wondering maybe an if-else condition before trying to expand the principal property in future versions would also help ... cheers.

**Comment by andyrobbins** [comment]
This is now fixed by #17 , thank you for opening this issue @mpras01 and for the helpful tip @doubley612
